### ISSUE TITLE
Where can I find 'main.py' for Chapter 5? Or should I do this by myself combining the codes of chapter5.ipynb. Thanks.

### ISSUE THREAD

**Issue by islomjn** [Apress/monetizing-machine-learning#2]

**Comment by amunategui** [comment]
It's all there - under 'web-application/' - best!

**Comment by islomjn** [comment]
thank you very much. I like your book!:)

**Comment by amunategui** [comment]
Glad you like it! Also lots of free walkthrough videos on related python topics at ViralML.com - best!
